CAMERA_INDEX = 0
FRAME_WIDTH = 640
FRAME_HEIGHT = 480

MODEL_PATH = "models/yolov8n.pt"
YOLO_CONFIDENCE = 0.45
YOLO_IOU = 0.50
YOLO_IMGSZ = 640
YOLO_EVERY_N_FRAMES = 1

WAKE_WORD = "jarvis"
KNOWN_OBJECT_REPEAT = 4.0
NEW_OBJECT_COOLDOWN = 0.6
SPEECH_RATE = 160

CENTER_ZONE_RATIO = 0.34
NEAR_OBJECT_AREA_RATIO = 0.12
HIGH_RISK_AREA_RATIO = 0.22
